# Generated by Django 3.0 on 2020-01-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('Sid', models.IntegerField()),
                ('Period1', models.CharField(max_length=20)),
                ('Period2', models.CharField(max_length=20)),
                ('Period3', models.CharField(max_length=20)),
                ('Period4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Fid', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Qual', models.CharField(max_length=20)),
                ('Mobileno', models.IntegerField()),
                ('Batch', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('Sid', models.IntegerField(blank='True', null='True')),
                ('C', models.IntegerField()),
                ('CPP', models.IntegerField()),
                ('Java', models.IntegerField()),
                ('Python', models.IntegerField()),
                ('Html', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=20)),
                ('mobilenumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('Sid', models.IntegerField(blank='True', default='', null='True')),
                ('Address', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('AdmDate', models.DateField()),
                ('Mobileno', models.IntegerField()),
                ('Batch', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Guardian', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
