# Generated by Django 3.0 on 2020-01-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('Sid', models.IntegerField()),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('Reason', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
