# Generated by Django 3.0 on 2020-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0007_auto_20200109_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.IntegerField()),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('Reason', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
