# Generated by Django 3.0 on 2020-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_leave_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_f',
            name='Fname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
