# Generated by Django 3.0 on 2020-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0009_leave_f_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_f',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
